name: running test, build image, push registry, deploy
on: [push]

jobs:
  runningtest:
    name: running test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.22"
      - name: run test
        run: go test -v ./... -cover

  buildimage:
    name: build image
    runs-on: ubuntu-latest
    needs: runningtest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build image
        run: docker build -t sawalrever23/learn-github-action:latest .

      - name: login registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push image
        run: docker push sawalrever23/learn-github-action:latest

  deployec2:
    name: deploy ec2
    runs-on: ubuntu-latest
    needs: buildimage
    steps:
      - uses: actions/checkout@v3

      - name: deploy ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd projects
            docker pull sawalrever23/learn-github-action:latest
            docker stop learn-github-action || true
            docker run -d -p 8080:8080 -it --rm --name learn-github-action sawalrever23/learn-github-action:latest

